### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by stephenlf** [stephenlf/rust-genai#2]
### Bug description

Testing testing

### Command

testsestd

### Error

testdsetse

### Config

```toml
[genai]
model = "gpt-4o"

[runtime]
# Default to 1 if absent
items_concurrency = 1
```

### Agent

```md
# Data

let path = item.path;
// ...


# Instruction

- The user will provide good error messages
- The information provided by the user will be helpful for debugging issues
- ...

# Output
```rhai
// ...
```
```


### Verbose output

```fundamental
$ devai run proof-comments
Running agent command: proof-comments
                  from: .devai/defaults/proof-comments.md
            with model: mistral:latest
# ...
```

### Additional information

# etdsdsetessetsed
